FROM bitnami/spark:3.5.3


ENV JAVA_OPTS="--add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED"

WORKDIR /opt/bitnami/spark


COPY src/main/resources/application.yaml /opt/bitnami/spark/conf/application.yaml


COPY scripts/run-spark-job.sh /opt/bitnami/spark/run-spark-job.sh


USER root


RUN apt-get update && apt-get install -y curl


RUN chown -R 1001:1001 /opt/bitnami/spark/jars && chmod -R 777 /opt/bitnami/spark/jars
RUN chmod +x /opt/bitnami/spark/run-spark-job.sh


USER 1001


CMD ["/bin/bash", "-i"]