include:
  - 'devops/postgres/docker-compose-postgres.yaml'
  - 'devops/clickhouse/docker-compose-clickhouse.yaml'
  - 'devops/cassandra/docker-compose-cassandra.yaml'
  - 'devops/neo4j/docker-compose-neo4j.yaml'
  - 'devops/mongo/docker-compose-mongo.yaml'
  - 'devops/valkey/docker-compose-valkey.yaml'
  - 'docker-compose-spark.yaml'

networks:
  shared:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  cassandra_data:
  clickhouse_data:
  neo4j_data:
  valkey_data:
