version: '3.8'

services:

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile-spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8000:8000'
      - '7077:7077'
    volumes:
      - ./target:/opt/bitnami/spark/jars
      - ./mock_data:/opt/bitnami/spark/data
      - ./src/main/resources/config.properties:/opt/bitnami/spark/conf/config.properties

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=sales_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - '6433:5432'
    volumes:
      - ./mock_data:/mock_data
    networks:
      - shared

  mongodb:
    image: mongo:7
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
     - shared

  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: clickhouse-db
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secret
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=sales_db
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - shared

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra-db
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_PASSWORD=secret
      - CASSANDRA_PASSWORD_SEEDER=yes
    volumes:
      - cassandra_data:/bitnami/cassandra
      - ./cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - shared

  neo4j:
    image: neo4j:5.23
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/password-secret
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data
      - ./neo4j/init-db.sh:/init-db.sh
    networks:
      - shared

  valkey:
      image: valkey/valkey:8.0
      container_name: valkey-db
      ports:
        - '6379:6379'
      volumes:
        - valkey_data:/data

networks:
  shared:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  cassandra_data:
  clickhouse_data:
  neo4j_data:
  valkey_data:
