FROM bitnami/spark:3.5.3

USER root


RUN apt-get update && apt-get install -y curl


COPY mock_data /opt/bitnami/spark/data


RUN chown -R 1001:1001 /opt/bitnami/spark/data /opt/bitnami/spark/jars && chmod -R 777 /opt/bitnami/spark/data /opt/bitnami/spark/jars

USER 1001

CMD ["sh", "-c", "if [ \"$SPARK_MODE\" = \"master\" ]; then /opt/bitnami/spark/sbin/start-master.sh; else /opt/bitnami/spark/sbin/start-worker.sh $SPARK_MASTER_URL; fi"]