  datasource:
    url: jdbc:postgresql://postgres:5432/sales_db
    username: admin
    password: secret

custom:
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace: sales

  clickhouse:
    url: jdbc:clickhouse://clickhouse:8123/sales_db
    user: admin
    password: secret

  neo4j:
    uri: bolt://neo4j:7687
    user: neo4j
    password: password-secret

spark:
  master: spark://spark-master:7077
  app-name: SnowflakeETLPipeline
  ui:
    enabled:
      false
input:
  csv:
    path: /opt/bitnami/spark/data/mock_data.csv
